---
{{ if .Values.service.loadbalancer.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: kanboard-lb
  annotations:
    {{- if .Values.service.loadbalancer.isMetalLb}}
    metallb.universe.tf/loadBalancerIPs: {{.Values.service.loadbalancer.ip}}
    metallb.universe.tf/allow-shared-ip: kanboard
    {{- end}}
    {{- if .Values.service.loadbalancer.isCilium}}
    io.cilium/lb-ipam-ips: {{.Values.service.loadbalancer.ip}}
    io.cilium/lb-ipam-sharing-key: kanboard
    {{- end}}
spec:
  type: LoadBalancer
  selector:
    app: kanboard
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadbalancer.ip }}
  {{ end }}